export class SongModel {

	public	title:string="Name of the song";
	public	date:Date=new Date();
	public	intro:string="There should be some text here, some introductory text, nothing large.... But we should be able to fill the whole thingy left and right and shit.";
	public	audio_url:string="";
	public	image_url:string="assets/images/pic.jpg";
	public	image_title:string="Title for the image";
	public	main_text:string="<p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p><p>Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description. Here goes an extended description.</p>"
	public	credits:string="<p>Check the padding on this shit... Seems broken. Check the padding on this shit... Seems broken. Check the padding on this shit... Seems broken. Check the padding on this shit... Seems broken. </p><ul><li>Here goes the list of shit.</li></ul>";

};
